### ISSUE TITLE
Issues with dll

### ISSUE THREAD

**Issue by Nathanhamm146** [andreaskeller96/HoloLens2-IRTracking-Sample#10]
Hi I have been trying to deploy and use this sample tracking tool, however, everytime I attempt deploy I am unable to visualize the tracking spheres as well as the tracking tool. When I check my unity log it also says. I was hoping you could provide some insight on the issue and how I can go about fixing it.
![unity player log image](https://github.com/user-attachments/assets/dcbabeaa-2c00-49fd-8fc1-4df06c991b29)

**Comment by andreaskeller96** [comment]
Hey, could you try updating the operating system on the HoloLens to the newest version?

**Comment by Nathanhamm146** [comment]
Hey I tried updating Windows but there is no change in the dll being unable to load

**Comment by andreaskeller96** [comment]
Are you building release or debug?

**Comment by andreaskeller96** [comment]
After some investigating on my side, it appears that the newest windows sdk causes this issue. In order to fix it, you need to compile the library from source (https://github.com/andreaskeller96/HoloLens2-IRTracking) and then replace the dll in Assets/HoloLensIRTracking/Plugins/WSA/ARM64 with the newly compiled one. This fixes the issue

**Comment by Nathanhamm146** [comment]
Ok thank you. That worked
